# Generated by Django 2.1.7 on 2019-03-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='titlechannel',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='usertrophy',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='entry',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
